### ISSUE TITLE
Arrow not shown

### ISSUE THREAD

**Issue by llKoull** [aleksandrshoshiashvili/AwesomeSpotlightView#22]
Hello!

When i set enableArrowDown to true, no arrow appears. i just do spotlightView.enableArrowDown = true. Should i do something else?

Thanks and best regards,

**Comment by FelipeABastos** [comment]
> Hello!
> 
> When i set enableArrowDown to true, no arrow appears. i just do spotlightView.enableArrowDown = true. Should i do something else?
> 
> Thanks and best regards,

Im having the same problem :(, did you solved yours?

**Comment by llKoull** [comment]
Hi @FelipeABastos !

No, i couldn't solve it, it could be solved forking the library and fixing It's code, but i didn't had time :S

**Comment by FelipeABastos** [comment]
Understood :( Im really needing this right now, I dont know what to do hehe

**Comment by FelipeABastos** [comment]
@llKoull Thanks for the answer o/

**Comment by aleksandrshoshiashvili** [comment]
@llKoull @FelipeABastos thank you for bringing this up. But unfortunately I couldn't reproduce this problem. Could you please check version 0.1.8? If it's still there then could you please share some piece of code to check how are you initialize spotlight view?

**Comment by PinguWithAnAxe** [comment]
Hello!

This problem occurred for me in 0.1.8. The problem seems to be that the library is trying to load arrowDownImage from the main bundle. As I had installed via cocoapods the path for the resource was returning nil as the library's bundle wasn't the main bundle.

The solution was to replace 
'if let bundlePath = Bundle.main.path(forResource: "AwesomeSpotlightViewBundle", ofType: "bundle")'
with
'if let bundlePath = Bundle(for: type(of: self)).path(forResource: "AwesomeSpotlightViewBundle", ofType: "bundle")'

After that it was able to find the resource.
